from __future__ import annotations

from shared.ai.zombie_ecology import DistrictSimulationState
from shared.models import Vec2


RAVEN_DISTRICTS = [
    DistrictSimulationState(
        id="downtown",
        title="Downtown",
        center=Vec2(5700.0, 2550.0),
        radius=1900.0,
        military_control=0.28,
        zombie_pressure=0.72,
        loot_remaining=0.92,
        danger_level=0.82,
        noise_level=0.38,
        infestation_level=0.78,
        civilian_population=0.12,
        military_strength=0.32,
        infrastructure_integrity=0.54,
        electricity_level=0.38,
        food_supply=0.42,
        medical_supply=0.35,
        morale=0.26,
        quarantine_level=0.44,
        tags=("high_loot", "elite_soldiers", "hordes", "narrow_streets"),
    ),
    DistrictSimulationState(
        id="residential",
        title="Residential",
        center=Vec2(2700.0, 4050.0),
        radius=1700.0,
        military_control=0.14,
        zombie_pressure=0.48,
        loot_remaining=0.62,
        danger_level=0.45,
        noise_level=0.12,
        infestation_level=0.44,
        civilian_population=0.58,
        military_strength=0.18,
        infrastructure_integrity=0.72,
        electricity_level=0.56,
        food_supply=0.46,
        medical_supply=0.36,
        morale=0.48,
        quarantine_level=0.16,
        tags=("houses", "survivors", "stealth"),
    ),
    DistrictSimulationState(
        id="industrial_zone",
        title="Industrial Zone",
        center=Vec2(9300.0, 6100.0),
        radius=1850.0,
        military_control=0.18,
        zombie_pressure=0.66,
        loot_remaining=0.72,
        danger_level=0.76,
        noise_level=0.28,
        infestation_level=0.7,
        civilian_population=0.08,
        military_strength=0.22,
        infrastructure_integrity=0.46,
        electricity_level=0.42,
        food_supply=0.24,
        medical_supply=0.22,
        morale=0.2,
        quarantine_level=0.28,
        tags=("factories", "toxic", "heavy_zombies"),
    ),
    DistrictSimulationState(
        id="military_blockade",
        title="Military Blockade",
        center=Vec2(9800.0, 2050.0),
        radius=1450.0,
        military_control=0.84,
        zombie_pressure=0.34,
        loot_remaining=0.78,
        danger_level=0.58,
        noise_level=0.22,
        infestation_level=0.36,
        civilian_population=0.18,
        military_strength=0.86,
        infrastructure_integrity=0.82,
        electricity_level=0.74,
        food_supply=0.68,
        medical_supply=0.72,
        morale=0.66,
        quarantine_level=0.88,
        tags=("checkpoints", "bunkers", "medics", "heavies"),
    ),
    DistrictSimulationState(
        id="hospital",
        title="Hospital",
        center=Vec2(4200.0, 6750.0),
        radius=1300.0,
        military_control=0.22,
        zombie_pressure=0.78,
        loot_remaining=0.88,
        danger_level=0.84,
        noise_level=0.18,
        infestation_level=0.82,
        civilian_population=0.16,
        military_strength=0.26,
        infrastructure_integrity=0.6,
        electricity_level=0.44,
        food_supply=0.28,
        medical_supply=0.86,
        morale=0.22,
        quarantine_level=0.4,
        tags=("medicine", "infected_patients", "screamers"),
    ),
    DistrictSimulationState(
        id="police_station",
        title="Police Station",
        center=Vec2(7150.0, 7100.0),
        radius=1150.0,
        military_control=0.42,
        zombie_pressure=0.52,
        loot_remaining=0.82,
        danger_level=0.66,
        noise_level=0.16,
        infestation_level=0.54,
        civilian_population=0.22,
        military_strength=0.48,
        infrastructure_integrity=0.68,
        electricity_level=0.58,
        food_supply=0.34,
        medical_supply=0.3,
        morale=0.38,
        quarantine_level=0.48,
        tags=("weapons", "trapped_officers", "riot_zombies"),
    ),
    DistrictSimulationState(
        id="underground_metro",
        title="Underground Metro",
        center=Vec2(6000.0, 4600.0),
        radius=2400.0,
        floor=-1,
        military_control=0.04,
        zombie_pressure=0.9,
        loot_remaining=0.48,
        danger_level=0.9,
        noise_level=0.25,
        infestation_level=0.96,
        civilian_population=0.02,
        military_strength=0.04,
        infrastructure_integrity=0.32,
        electricity_level=0.08,
        food_supply=0.1,
        medical_supply=0.08,
        morale=0.06,
        quarantine_level=0.18,
        tags=("darkness", "hordes", "metro"),
    ),
]
